name: Build

on:
  - push 

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    runs-on: ${{ matrix.os }}
  strategy:
    os: [macos-latest, ubuntu-latest, windows-latest]

  steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
